### ISSUE TITLE
Use the new OAuth2 endpoint for authentication

### ISSUE THREAD

**Issue by willemarcel** [OSMCha/osmcha-frontend#562]
OSM now supports OAuth2 to authentication: https://wiki.openstreetmap.org/wiki/OAuth

**Comment by mmd-osm** [comment]
OSM's OAuth 1.0a is in the process of being deprecated, as discussed at https://github.com/openstreetmap/operations/issues/867. No timeline has been set, but we do not expect to shut off OAuth 1.0a this year. It would be good to move to OAuth 2.0 well before this time.

**Comment by tordans** [comment]
I might be worth checking https://www.npmjs.com/package/osm-auth out to move the auth flow to a library.

**Comment by mmd-osm** [comment]
Update on timelines for sunsetting OAuth 1.0a: https://community.openstreetmap.org/t/oauth-1-0a-and-http-basic-auth-shutdown/108490

**Comment by mmd-osm** [comment]
Another update: https://blog.openstreetmap.org/2024/04/17/oauth-1-0a-and-http-basic-auth-shutdown-on-openstreetmap-org/

* May 1st, 2024: System administrators will start brownouts to find applications that are still using OAuth 1.0a or HTTP Basic Auth.
* June 1st, 2024: OAuth 1.0a and HTTP Basic Auth will be shut down.

**Comment by mnalis** [comment]
- https://mapcontrib.xyz -  https://gitlab.com/mapcontrib/mapcontrib.next/-/issues/51

**Comment by mnalis** [comment]
Reminder: June 1st, 2024 is this upcoming weekend, and Login will [stop working then](https://community.openstreetmap.org/t/oauth-1-0a-and-http-basic-auth-shutdown/108490/16) unless this is fixed and OAuth2 is implemented.

_(And thanks to everyone working hard on this! :heart:)_

**Comment by willemarcel** [comment]
OSMCha is now using OAuth2!
