### ISSUE TITLE
Osmcha doesn't update anymore

### ISSUE THREAD

**Issue by ivanbranco** [OSMCha/osmcha-frontend#678]
## *Brief Description*
Osmcha didn't update for 10 hours. The latest global changeset Osmcha shows me is this one: https://osmcha.org/changesets/139988845 
I tried logging out and in and deleting the browser caches but nothing changed.

## Please tell us about your environment:
Google Chrome V115.0.5790.171

**Comment by batpad** [comment]
@ivanbranco I'm seeing recent changesets - for eg. from 30 mins ago: https://osmcha.org/changesets/140007931

Is it not updating for you? That would be really strange 🤔

**Comment by ivanbranco** [comment]
Now it works for me too, but something happened around 10 hours ago for sure, e.g. it shows me only two changesets in the "9 hours ago" time range in the whole world (which is not possible - in the last 30 minutes around 1100 changeset were submitted, according to OSMcha): 
![image](https://github.com/mapbox/osmcha-frontend/assets/94002623/c7313174-66ec-4d27-ad65-01bb00f61a93)
Most of the changeset listed around that time seem to have a comment. So I guess those without comment got lost somehow?

Anyway, it works now, so I guess it can be closed.

**Comment by batpad** [comment]
@ivanbranco - it's very likely / possible that some of the backend infrastructure had a blip. Thankfully it resolved :-) thank you for reporting.

**Comment by batpad** [comment]
Hmmm although it's a bit strange that there are no changesets for that time period - OSMCha should show the timestamp of the changeset, and not the timestamp when it was ingested (even if it was ingested later due to some infrastructure issue). Hmmm...

**Comment by batpad** [comment]
> So I guess those without comment got lost somehow?

This is curious indeed :-) would you mind pasting the full URL for the search query you are performing here?

**Comment by ivanbranco** [comment]
> > So I guess those without comment got lost somehow?
> 
> This is curious indeed :-) would you mind pasting the full URL for the search query you are performing here?

No query (it's also visible in the screenshot, there's no filter active), I just went back in time in the main page with the global changesets, so the full url was https://osmcha.org/ . I didn't touch "Ordered by" neither, is the default value.

**Comment by willemarcel** [comment]
![image](https://github.com/mapbox/osmcha-frontend/assets/666291/ad1e05ad-f185-4f88-b32b-b1ae157269b7)
The OSM replication files had a 11 hours gap. Probably this was the cause of the disruption.

**Comment by batpad** [comment]
😨 thanks @willemarcel :-)

**Comment by ivanbranco** [comment]
Seems like this happened again? Or is just me? The last changeset I can see is from 10 hours ago
