### ISSUE TITLE
Can't set flags

### ISSUE THREAD

**Issue by Kovoschiz** [OSMCha/osmcha-frontend#705]
## *Brief Description*

Set flags (I don't really care about thumbs up/down) 

## What  is the current behaviour, (attach relevant screenshots) ?

Flags menu doesn't show. No console messages. 

## What  is the expected behaviour ?

At least the flags menu should show up (then I can try to select the flags to see if that works)

## When does this occur ?

Always. I checked that https://osmcha.org/api/v1/changesets/*/set-good/ etc requests are successful.  

## How do we replicate the issue ?

1. Rate good/bad 
2. Click "Tags"

## Please tell us about your environment:

* Firefox 122.0 
   * Enhanced Tracking Protection off (I forgot how to unblock this one Google Analytics thing on basic protection, but it shouldn't matter?)
   * DuckDuckGo Privacy Essentials disabled
   * NoScript allowed all  
* Linux Mint 20.2

## Other Information / context:

The only major non-CSS error that appeared a while afterwards: 
```
TypeError: s is null
    ra changesets_page_actions.js:149
    c runtime.js:63
    _invoke runtime.js:293
    y runtime.js:118
    Redux 43
    <anonymous> navbar_changeset.js:129
    handleClick dropdown.js:41
    React 12
    unstable_runWithPriority scheduler.production.min.js:19
    React 3
    o raven.js:376
    o raven.js:1202
    React 15
    227 index.js:42
    a 147466859:1
    120 main.08ed5f19.chunk.js:1
    a 147466859:1
    t 147466859:1
    r 147466859:1
    <anonymous> main.08ed5f19.chunk.js:1
console.js:35:31
``` 
(Per `// this fails for some browsers. :(` comment, and naming, it seems unrelated) 
At least 32 `WebGL warning: texImage: Alpha-premult and y-flip are deprecated for non-DOM-Element uploads.`  (not reported afterwards) 
CSS: 
* Many `Error in parsing value for ‘user-select’.  Declaration dropped. <changeset>:1:1`
* A few of this
```
Ruleset ignored due to bad selector. assembly.min.css:1:102125
Ruleset ignored due to bad selector. assembly.min.css:1:102361
Ruleset ignored due to bad selector. assembly.min.css:1:102434
Ruleset ignored due to bad selector. assembly.min.css:1:102579
``` 
* `Unknown pseudo-class or pseudo-element ‘-ms-fill-upper’.  Ruleset ignored due to bad selector.` etc 
* `Expected media feature name but found ‘-ms-high-contrast’.` 
* 
If you need a HAR file etc, you can give me a changeset to try. Don't want to try rating random changesets arbitrarily.

**Comment by mxxcon** [comment]
Happens for me on both Chrome and Firefox
