### ISSUE TITLE
Changesets missing from filter results

### ISSUE THREAD

**Issue by elevenchars** [OSMCha/osmcha-frontend#706]
## *Brief Description*

There appear to be some changesets missing from the downtime. This is important for people who do QA for an area/type of edit using OSMCha filters.

## What  is the current behaviour, (attach relevant screenshots) ?

![image](https://github.com/OSMCha/osmcha-frontend/assets/11055681/cd77eab1-ca83-4373-be59-790c598a5150)
Notice that [changeset 147430472](https://www.openstreetmap.org/changeset/147430472) is missing from the filter results.

## What  is the expected behaviour ?

The filter results should include all changesets which match it.

## When does this occur ?

The conditions for this to occur are unclear, I just happened to notice it when I opened OSMCha after the downtime.

## How do we replicate the issue ?

1. Filter to changesets by citrula [link](https://osmcha.org/?filters=%7B%22uids%22%3A%5B%7B%22label%22%3A%2216979815%22%2C%22value%22%3A%2216979815%22%7D%5D%2C%22date__gte%22%3A%5B%7B%22label%22%3A%22%22%2C%22value%22%3A%22%22%7D%5D%7D)
2. Compare to changesets listed at [citrula's OpenStreetMap profile](https://www.openstreetmap.org/user/citrula/history)
3. Notice that there is a changeset missing

## Please tell us about your environment:

I'm using Firefox 122.0 (64-bit) and the production instance located at https://osmcha.org.

## Other Information / context:

@batpad requested I open an issue here after I mentioned this issue in Slack.

**Comment by emersonveenstra** [comment]
Changesets 147448293 and 147448264 are missing for me as well

**Comment by batpad** [comment]
Thanks @elevenchars @emersonveenstra ! My hunch is this happened during the 48 hour period or so when we were hitting db throttling issues. We can attempt to re-run / backfill changeset files for those days. If this does seem to be continuing to happen, then it's definitely a matter of concern and we'll go through logs a bit better to try and figure what's happening.

**Comment by MithunMGowda** [comment]
20th may all changeset are missing, I can barely find only one.

**Comment by felipeedwards** [comment]
Hello. Running some filters now. It seems to be a huge gap, but not only from 20th... the filter gives me 6 changesets for a hole country in the last 24 hours, which is not real.
thanks

**Comment by cliffordsnow** [comment]
Not sure this is the same issue, but while reviewing new users in Washington State, user MIJoeB is shown to have 3 changesets by OSMCha, but only shows 2 when asked to show all of their changesets.

Pulling from OSM data I see:
changesets=# select id,user_id,user_name,tags->'comment' from osm_changeset where user_id = 21081684;
    id     | user_id  | user_name |       comment      
-----------+----------+-----------+-----------------------
 147833372 | 21081684 | MIJoeB    | added proper driveway
 147833588 | 21081684 | MIJoeB    | updated address
 147833600 | 21081684 | MIJoeB    | updated address

The last changeset, 147833600, is missing from the list.

**Comment by willemarcel** [comment]
I backfilled the missing changesets. Let me know if you identify some others that are missing.

**Comment by felipeedwards** [comment]
thank you very much. I´ll check out

**Comment by emersonveenstra** [comment]
148305067 is missing from OSMCha

**Comment by emersonveenstra** [comment]
148325316 and 148356889 are missing from the past day.
