### ISSUE TITLE
Changeset Flags Filter is not Working

### ISSUE THREAD

**Issue by mapdevsaikat** [OSMCha/osmcha-frontend#709]
## *Brief Description*
I am unable to add any `Reasons for Flagging` filters from the list.

## What is the motivation / use case for this feature?
I am using it to filter some selected flags that are related to `name` change and `highway` geometry modification.

## What  is the current behaviour, (attach relevant screenshots) ?

![osmcha_filter_bug](https://github.com/OSMCha/osmcha-frontend/assets/67556186/28fd344b-4e16-454d-8fa3-ec63fca60547)

## What  is the expected behaviour ?

![osmcha_reason_for_flag](https://github.com/OSMCha/osmcha-frontend/assets/67556186/5a00a991-a79d-4e5a-b6af-68e1bc059674)

## When does this occur?
After the infrastructure migration.

## How do we replicate the issue ?
1. Start typing the OSMCha flags under the `Reasons for Flagging` in the `Filter` option.

## Please tell us about your environment:
Chrome: Version 121.0.6167.160
Brave: Version 1.62.165

## Other Information / context:

@batpad

**Comment by mapdevsaikat** [comment]
Hi @willemarcel , thanks for the fix, but the `Filter` is not working it seems. Please check the error message.

<img width="318" alt="filter_error" src="https://github.com/OSMCha/osmcha-frontend/assets/67556186/3ca8659d-6d7a-45d1-9710-87a6059cf344">

**Comment by andrewtwelch** [comment]
Can confirm this is still occuring, am getting the same error whenever filtering using Reasons for Flagging.

**Comment by willemarcel** [comment]
@andrewtwelch @mapdevsaikat could you send me a link of a filter with that error? I'm not able to reproduce it.

**Comment by willemarcel** [comment]
I believe now it's solved (#714)
