### ISSUE TITLE
Changeset number missing from RSS feed

### ISSUE THREAD

**Issue by Mannivu** [OSMCha/osmcha-frontend#710]
## *Brief Description*
The changeset number is missing from RSS feed and the feed doesn't work properly

## What  is the current behaviour, (attach relevant screenshots) ?
![IMG_20240217_085910](https://github.com/OSMCha/osmcha-frontend/assets/42747216/bb9d9633-e235-4049-ac76-82fbc74f8cc4)

## What  is the expected behaviour ?
![IMG_20240217_090017](https://github.com/OSMCha/osmcha-frontend/assets/42747216/50d60fcf-4465-4749-ad08-08e1e76ff372)

## When does this occur ?
I every RSS feed

## How do we replicate the issue ?

1. Subscribe to any filter RSS 
2. See the error in every new alert

## Please tell us about your environment:
Not relevant

**Comment by willemarcel** [comment]
Fixed by https://github.com/OSMCha/osmcha-django/pull/677
