### ISSUE TITLE
Placing a comment in the comment field will not be posted.

### ISSUE THREAD

**Issue by FransS1945** [OSMCha/osmcha-frontend#712]
Since last revision of OSMcha it is not possible to post a message to the mapper. 
A message "it was not possible to post a message'  was shown and the message was not send.

## *Brief Description*
I often review changesets of (new) mappers or mappers who request a review.
Main reason is to give feedback to the mappers about their mapping quality and issues they cause.
Now I am unable to respond.

## How do we replicate the issue ?

1. select a changeset in JOSM
2.select open in OSMcha
3.open the dialog field
4.add some text and  post the comment.

## Please tell us about your environment:
Use Firefox on Window. latest revision

## Other Information / context:
It appeared after moving OSMcha to another server.

**Comment by FransS1945** [comment]
![OSMcha message not posted](https://github.com/OSMCha/osmcha-frontend/assets/31804031/211336c3-fa16-4ea6-ab99-bb964969e0de)

**Comment by willemarcel** [comment]
@FransS1945 thanks for reporting. It's fixed now!
