### ISSUE TITLE
RSS feeds are no longer following the RSS specification

### ISSUE THREAD

**Issue by emersonveenstra** [OSMCha/osmcha-frontend#715]
## *Brief Description*
RSS feeds are reported as invalid by W3C RSS feed checker

## What  is the current behaviour, (attach relevant screenshots) ?
see https://validator.w3.org/feed/check.cgi?url=https://osmcha.org/api/v1/aoi/9c5e20c2-f8c3-46d3-8ed4-4bd0040d8b9a/changesets/feed/

## What  is the expected behaviour ?
RSS feeds are valid

**Comment by willemarcel** [comment]
It's fixed now!
