### ISSUE TITLE
Posting discussion comments through osmcha gives error

### ISSUE THREAD

**Issue by arjunaraoc** [OSMCha/osmcha-frontend#720]
## *Brief Description*

When I try add a discussion comment to a changeset using OSMCha, it gives error. "It was not possible to post your comment".  This error arose after the port of OSMCha on 13 Feb 2024
## What  is the current behaviour, (attach relevant screenshots) ?

Screenshot enclosed
![Osmcha discussion posting error 2024-03-01 15-46-06](https://github.com/OSMCha/osmcha-frontend/assets/524249/59e79549-5354-47c2-a9f6-65a1b97b176a)

## What  is the expected behaviour ?

Discussion comment should be posted successfully
## When does this occur ?

Everytime a comment posting is attempted
## How do we replicate the issue ?

1. Take any changeset and try to post a comment.
2. The error shows
3.
4.

## Please tell us about your environment:

Ubuntu 22.04, Firefox 123.0(64bit)
## Other Information / context:

This error seems to be a result of the porting of Osmcha to new server on 13 Feb 2024

**Comment by willemarcel** [comment]
Are you still experiencing this issue? I could not reproduce it.

**Comment by arjunaraoc** [comment]
Yes, I tried with Chrome Version 121.0.6167.184 (Official Build) (64-bit) also and faced the same error

**Comment by arjunaraoc** [comment]
Looks like cookie issue. I logged out and then logged in. Now I am able to post comments.

**Comment by tordans** [comment]
@willemarcel I was having the same issue. Is there a way to invalidate cookies that belong to the old OAuth Process? Which I guess is the issue here…?
