### ISSUE TITLE
Comments on changesets not appearing in OSMCha changeset list or appropriate filters

### ISSUE THREAD

**Issue by andrewtwelch** [OSMCha/osmcha-frontend#727]
## *Brief Description*
The count of comments on changesets don't seem to be showing up in OSMCha, resulting in filtering by comments not working. Comments still show if a changeset is viewed and the comments tab selected.

## What  is the current behaviour, (attach relevant screenshots) ?
No comment count on changeset listing, changesets with comments missing from a filter looking at changesets with at least one comment.
![image](https://github.com/OSMCha/osmcha-frontend/assets/10568504/f9932836-a592-4d06-99fc-1948438da6cf)

## What  is the expected behaviour ?
Comment count shows and these changesets show in the appropriate filter.

## When does this occur ?
Has been occurring for a couple of days.

## How do we replicate the issue ?
1. Look at any changeset in the left side list that has comments on the changeset. Changeset 150053524 is a good example.

## Please tell us about your environment:
Occurring across all browsers tested, appears to be a backend data issue.

**Comment by andrewtwelch** [comment]
I'm starting to see some newer changesets showing comments, there's a decent gap still and I'm not sure if new ones are loading yet, but it seems like something is working again.

**Comment by nrenner** [comment]
Was probably caused by this OSM API bug (now fixed):
- https://github.com/zerebubuth/openstreetmap-cgimap/issues/401

**Comment by mmd-osm** [comment]
It's really unexpected that the changeset comment filtering in OSMCha is impacted by the OSM API regression. I'm wondering at what point in time they're calling the API and how they manage to keep the number of changeset comments up to date.

**Comment by willemarcel** [comment]
The number of comments is updated every time the changeset receives a new comment, as the changeset will be again in a replication file. We were having some bugs in the changeset ingestion pipeline, that probably caused this issue, but it's now fixed.
We use the OSM API to show the comments in the frontend.

**Comment by andrewtwelch** [comment]
That makes perfect sense, seems to be working perfectly now.
