### ISSUE TITLE
OSMCha will not open.

### ISSUE THREAD

**Issue by FransS1945** [OSMCha/osmcha-frontend#732]
## *Brief Description*
OSMCHa will not open. Both in firefox and Chrome

## Please tell us about your environment:
Windows Home 11  Firefox 126.0 64 bit
Chrome Versie 125.0.6422.78 (Officiële build) (64-bits)

**Comment by batpad** [comment]
I could reproduce this earlier, but it seems like it works now.

@willemarcel I was seeing a 500 error on the `/v1/social_auth` or so end-point. My hunch is this might be osm.org prepping for the impending upgrade to OAuth2? Maybe? 

@FransS1945 can you confirm this works again for you now, or is it still broken?

Thanks much for the report!

**Comment by FransS1945** [comment]
It works again. Thanks






Frans


Op ma 27 mei 2024 om 16:30 schreef Sanjay Bhangar ***@***.***>

**Comment by mmd-osm** [comment]
Yes, there was a 1h brownout today starting at 09:15 UTC, as announced in https://blog.openstreetmap.org/2024/04/17/oauth-1-0a-and-http-basic-auth-shutdown-on-openstreetmap-org/
