### ISSUE TITLE
I can't open my saved OSMCha filter

### ISSUE THREAD

**Issue by adiatmad** [OSMCha/osmcha-frontend#734]
## *Brief Description*
I can't open my saved filter. 
<img width="276" alt="TypeError" src="https://github.com/OSMCha/osmcha-frontend/assets/38268616/45b143f4-c5db-41e3-ab4f-d4045f5cac51">

## How do we replicate the issue ?
I can't open this saved filter
1. https://osmcha.org/filters?aoi=74211d3d-6704-4e48-b438-b3980c7d9508
2. https://osmcha.org/filters?aoi=440984a4-c08e-4a08-95ec-944814807326
3. https://osmcha.org/filters?aoi=67e80e55-5e15-4d45-adf3-660ca5fed7dd

## Please tell us about your environment:
Firefox 126.0.1 (64-bit). Windows 11

**Comment by willemarcel** [comment]
Thanks for reporting, @adiatmad ! It's now fixed.
